### ISSUE TITLE
找不到地图数据 Maps not found

### ISSUE THREAD

**Issue by zhangzhe1111** [Dingrui-Wang/ESP-Dataset#1]
请问你们的数据集有包含地图数据吗

**Comment by Dingrui-Wang** [comment]
之前的下载链接已过期，您可以在[这里](https://huggingface.co/datasets/Etadingrui/ESP)找到包含地图的更新链接。感谢您的提醒！

The previous download link is outdated. You can find the updated link, which includes the Maps, [here](https://huggingface.co/datasets/Etadingrui/ESP). Thank you for bringing this to our attention!
