### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by zhangzhe1111** [Dingrui-Wang/ESP-Dataset#2]
你好，请问数据处理部分代码方便开源吗？

**Comment by bulbcult** [comment]
您好，数据处理部分代码您指的具体是什么，是数据可视化还是数据生成？

**Comment by zhangzhe1111** [comment]
感谢大佬回复，数据生成的吧，方便了解一下数据具体结构

**Comment by bulbcult** [comment]
您是指的由感知数据到sample的生成代码吗

**Comment by zhangzhe1111** [comment]
把数据处理成TNT和MTR使用的数据处理的代码

**Comment by bulbcult** [comment]
我们把代码清理一下，本周末之前会开源

**Comment by Dingrui-Wang** [comment]
> 把数据处理成TNT和MTR使用的数据处理的代码

Please find the related code in newly updated folder: tools

**Comment by BecomeLoser** [comment]
你好请问一下数据预处理的出来的数据直接可以在MTR中跑通吗

**Comment by penglo** [comment]
你好,请问数据预处理的出来的数据直接可以在MTR中跑通吗.万分感激

**Comment by BecomeLoser** [comment]
> 我们把代码清理一下，本周末之前会开源
大佬您好,不知道你你是否方便开源一下关于mtr使用该数据集跑通的代码呢,如果可以的话,万分感激,祝科研顺利,万事如意
